backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages English"
    files:
      - file: "src/pages/en/index.md"
        label: "Home"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Quote"
            name: "quote"
            widget: "object"
            fields:
              - { label: "Quote Text", name: "text", widget: "string" }
              - { label: "Quote Footer", name: "footer", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/en/team/index.md"
        label: "Team"
        name: "team"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Bev"
            name: "bev"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Nationality", name: "nationality", widget: "string" }
              - { label: "Certificates", name: "certificates", widget: "list" }
          - label: "Angela"
            name: "angela"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Nationality", name: "nationality", widget: "string" }
              - { label: "Certificates", name: "certificates", widget: "list" }

      - file: "src/pages/en/fees/index.md"
        label: "Fees"
        name: "fees"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Group Lessons"
            name: "groupLessons"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Normal rate per Semester,
                  name: normalRateSemester,
                  widget: string,
                }
              - {
                  label: Reduced rate per Semester,
                  name: reducedRateSemester,
                  widget: string,
                }
          - label: "Private Lessons"
            name: "privateLessons"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: 1 person, name: one, widget: string }
              - { label: 3 person, name: two, widget: string }
              - { label: 3 person, name: three, widget: string }

      - file: "src/pages/en/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Bev"
            name: "bev"
            widget: "object"
            fields:
              - { label: "Telephone", name: "tel", widget: "string" }
              - { label: "E-Mail", name: "email", widget: "string" }
          - label: "Angela"
            name: "angela"
            widget: "object"
            fields:
              - { label: "Telephone", name: "tel", widget: "string" }
              - { label: "E-Mail", name: "email", widget: "string" }

      - file: "src/pages/en/courses/index.md"
        label: "Courses"
        name: "courses"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Days"
            name: "days"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - label: "Courses"
                name: "courses"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Level", name: "level", widget: "string" }
                  - { label: "CEF Level", name: "cefLevel", widget: "string" }

  - name: "pages-de"
    label: "Pages German"
    files:
      - file: "src/pages/de/index.md"
        label: "Home"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Quote"
            name: "quote"
            widget: "object"
            fields:
              - { label: "Quote Text", name: "text", widget: "string" }
              - { label: "Quote Footer", name: "footer", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/de/team/index.md"
        label: "Team"
        name: "team"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Bev"
            name: "bev"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Nationality", name: "nationality", widget: "string" }
              - { label: "Certificates", name: "certificates", widget: "list" }
          - label: "Angela"
            name: "angela"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Nationality", name: "nationality", widget: "string" }
              - { label: "Certificates", name: "certificates", widget: "list" }

      - file: "src/pages/de/fees/index.md"
        label: "Fees"
        name: "fees"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Group Lessons"
            name: "groupLessons"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Normal rate per Semester,
                  name: normalRateSemester,
                  widget: string,
                }
              - {
                  label: Reduced rate per Semester,
                  name: reducedRateSemester,
                  widget: string,
                }
          - label: "Private Lessons"
            name: "privateLessons"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: 1 person, name: one, widget: string }
              - { label: 3 person, name: two, widget: string }
              - { label: 3 person, name: three, widget: string }

      - file: "src/pages/de/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Bev"
            name: "bev"
            widget: "object"
            fields:
              - { label: "Telephone", name: "tel", widget: "string" }
              - { label: "E-Mail", name: "email", widget: "string" }
          - label: "Angela"
            name: "angela"
            widget: "object"
            fields:
              - { label: "Telephone", name: "tel", widget: "string" }
              - { label: "E-Mail", name: "email", widget: "string" }

      - file: "src/pages/de/courses/index.md"
        label: "Courses"
        name: "courses"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Days"
            name: "days"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - label: "Courses"
                name: "courses"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Level", name: "level", widget: "string" }
                  - { label: "CEF Level", name: "cefLevel", widget: "string" }
