backend:
  name: github
  repo: justmejulian/english-rafzerfeld
  branch: main
local_backend: true

media_folder: "public/assets/" # The folder where user-uploaded files are stored
public_folder: "assets/" # The src attribute for uploaded media

collections:
  - label: "Pages"
    name: "pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "src/content/home.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
