backend:
  name: github
  repo: justmejulian/english-rafzerfeld
  branch: main
local_backend: true

media_folder: 'public/assets/' # The folder where user-uploaded files are stored
public_folder: '/assets/' # The src attribute for uploaded media

i18n:
  structure: single_file
  locales: [en, de]

collections:
  - label: 'Pages'
    name: 'pages'
    i18n:
      structure: single_file
      locales: [en, de]
    files:
      - name: 'home'
        label: 'Home Page'
        file: 'src/content/home.json'
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - { label: Intro, name: intro, widget: markdown, i18n: true }
      - name: 'courses'
        label: 'Courses Page'
        file: 'src/content/courses.json'
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - label: Days
            name: days
            widget: list
            i18n: true
            fields:
              - { label: Name, name: name, widget: string, i18n: true }
              - label: Lessons
                name: lessons
                widget: list
                i18n: true
                fields:
                  - { label: Time, name: time, widget: string, i18n: true }
                  - { label: Level, name: level, widget: string, i18n: true }
                  - {
                      label: 'CEF Level',
                      name: ceflevel,
                      widget: string,
                      i18n: true,
                    }
          - {
              label: 'Levels Title',
              name: levelsTitle,
              widget: string,
              i18n: true,
            }
          - {
              label: 'Levels Desctiption',
              name: levelsDescription,
              widget: string,
              i18n: true,
            }
          - label: Levels
            name: levels
            widget: list
            i18n: true
            fields:
              - { label: Name, name: name, widget: string, i18n: true }
              - {
                  label: Description,
                  name: description,
                  widget: string,
                  i18n: true,
                }
              - label: 'Sub Levels'
                name: subLevels
                widget: list
                i18n: true
                fields:
                  - { label: Name, name: name, widget: string, i18n: true }
                  - {
                      label: Description,
                      name: description,
                      widget: string,
                      i18n: true,
                    }
      - name: 'team'
        label: 'Team Page'
        file: 'src/content/team.json'
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - label: Teachers
            name: teachers
            widget: list
            i18n: true
            fields:
              - { label: Name, name: name, widget: string, i18n: true }
              - { label: Description, name: description, widget: string, i18n: true }
              - { label: Image, name: image, widget: image}
              - { label: Nationality, name: nationality, widget: string, i18n: true }
              - label: 'Certificates'
                name: certificates
                widget: list
                i18n: true
                fields:
                  - { label: Name, name: name, widget: string, i18n: true }
