backend:
  name: github
  repo: justmejulian/english-rafzerfeld
  branch: main
local_backend: true

media_folder: "public/assets/" # The folder where user-uploaded files are stored
public_folder: "assets/" # The src attribute for uploaded media

i18n:
  structure: single_file
  locales: [en, de]

collections:
  - label: "Pages"
    name: "pages"
    i18n:
      structure: single_file
      locales: [en, de]
    files:
      - name: "home"
        label: "Home Page"
        file: "src/content/home.json"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Intro, name: intro, widget: markdown, i18n: true}
