backend:
  name: github
  repo: justmejulian/english-rafzerfeld
  branch: main
local_backend: true

media_folder: 'public/assets/' # The folder where user-uploaded files are stored
public_folder: '/assets/' # The src attribute for uploaded media

i18n:
  structure: single_file
  locales: [en, de]

# Todo create a collection for teachers

collections:
  - label: 'Pages'
    name: 'pages'
    i18n:
      structure: single_file
      locales: [en, de]
    files:
      - name: 'home'
        label: 'Home Page'
        file: 'src/content/home.json'
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - { label: Intro, name: intro, widget: markdown, i18n: true }
      - name: 'courses'
        label: 'Courses Page'
        file: 'src/content/courses.json'
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          # todo use select widget for days
          - label: Days
            name: days
            widget: list
            i18n: true
            fields:
              - { label: Name, name: name, widget: string, i18n: true }
              - label: Lessons
                name: lessons
                widget: list
                i18n: true
                fields:
                  - { label: Time, name: time, widget: string, i18n: true }
                  # todo use select widget for days
                  - { label: Level, name: level, widget: string, i18n: true }
                  - {
                      label: 'CEF Level',
                      name: ceflevel,
                      widget: string,
                      i18n: true,
                    }
          - {
              label: 'Levels Title',
              name: levelsTitle,
              widget: string,
              i18n: true,
            }
          - {
              label: 'Levels Desctiption',
              name: levelsDescription,
              widget: string,
              i18n: true,
            }
          - label: Levels
            name: levels
            widget: list
            i18n: true
            fields:
              - { label: Name, name: name, widget: string, i18n: true }
              - {
                  label: Description,
                  name: description,
                  widget: string,
                  i18n: true,
                }
              - label: 'Sub Levels'
                name: subLevels
                widget: list
                i18n: true
                fields:
                  - { label: Name, name: name, widget: string, i18n: true }
                  - {
                      label: Description,
                      name: description,
                      widget: string,
                      i18n: true,
                    }
      - name: 'team'
        label: 'Team Page'
        file: 'src/content/team.json'
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - label: Teachers
            name: teachers
            widget: list
            i18n: true
            fields:
              - { label: Name, name: name, widget: string, i18n: true }
              - { label: Description, name: description, widget: string, i18n: true }
              - { label: Image, name: image, widget: image}
              - { label: Nationality, name: nationality, widget: string, i18n: true }
              - label: 'Certificates'
                name: certificates
                widget: list
                i18n: true
                fields:
                  - { label: Name, name: name, widget: string, i18n: true }
      - name: 'fees'
        label: 'Fees Page'
        file: 'src/content/fees.json'
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - { label: 'Group Courses Title', name: groupCoursesTitle, widget: string, i18n: true }
          - { label: 'Group Courses Description', name: groupCoursesDescription, widget: string, i18n: true }
          - label: 'Group Courses'
            name: groupCourses
            widget: list
            i18n: true
            fields:
              - { label: Length, name: length, widget: number, i18n: true }
              - { label: 'Normal rate', name: normalRate, widget: number, i18n: true }
              - { label: 'Reduced rate', name: reducedRate, widget: number, i18n: true }
              - { label: 'Description', name: description, widget: markdown, i18n: true }
          - { label: 'Private Courses Title', name: privateCoursesTitle, widget: string, i18n: true }
          - { label: 'Private Courses Description', name: privateCoursesDescription, widget: string, i18n: true }
          - label: 'Private Courses'
            name: privateCourses
            widget: list
            i18n: true
            fields:
              - { label: Length, name: length, widget: number, i18n: true }
              - { label: '1 Person Rate', name: onePersonRate, widget: number, i18n: true }
              - { label: '2 Persons Rate', name: twoPersonsRate, widget: number, i18n: true }
              - { label: '3 Persons Rate', name: threePersonsRate, widget: number, i18n: true }
              - { label: 'Description', name: description, widget: markdown, i18n: true }
      - name: 'contact'
        label: 'Contact Page'
        file: 'src/content/contact.json'
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - { label: description, name: description, widget: markdown, i18n: true }
          - { label: email, name: email, widget: string, i18n: true }
          - label: 'Teachers Contact'
            name: teachersContact
            widget: list
            i18n: true
            fields:
              - { label: Name, name: name, widget: string, i18n: true }
              - { label: Email, name: email, widget: string, i18n: true }
              - { label: Phone, name: phone, widget: string, i18n: true }
          - { label: address, name: address, widget: string, i18n: true }

